version: "2"
exclude_patterns:
- rasa/core/utils.py   # codeclimate has some encoding issues with this files because of emojis
- rasa/utils/tensorflow/temp_keras_modules.py # largely copy paste and temporary
- .*
- .github/
- CHANGELOG.mdx
- CODEOWNERS
- CODE_OF_CONDUCT.md
- Dockerfile
- LICENSE.txt
- Makefile
- NOTICE
- PRONCIPLES.md
- README.md
- bandit.yml
- binder/
- changelog/
- data/
- docs/
- examples/
- poetry.lock
- pyproject.toml
- pytest.ini
- tests/
- stubs/
- setup.cfg
- scripts/
- security.txt
- secrets.tar.enc
checks:
  argument-count:
    config:
      threshold: 10
  file-lines:
    enabled: false
  method-count:
    enabled: false
