version: "3.8"

services:
  redis:
    image: redis:6
    # Set health checks to wait until redis has started
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

    ports:
      - 6379:6379

  postgres:
    image: postgres:13
    # Set health checks to wait until postgres has started
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      # postgres image requires password to be set
      PGUSER: ${PGUSER}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  rabbitmq:
    image: healthcheck/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - 5672:5672
